@host = http://localhost:5254

###

POST {{host}}/create
Accept: application/json
Content-Type: application/json

{ "url": "https://github.com/RomanEmreis/shorty" }

###

GET {{host}}/oQQQQQo
Accept: application/json

###

GET {{host}}/health
Accept: application/json

###
